function Grav_Joint_Sp = Grav_leg(in1,in2)
%GRAV_LEG
%    GRAV_JOINT_SP = GRAV_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Nov-2021 15:49:01

c5 = in2(20,:);
g = in2(30,:);
k = in2(31,:);
l_AC = in2(23,:);
l_A_m3 = in2(18,:);
l_B_m2 = in2(17,:);
l_C_m4 = in2(19,:);
l_C_s = in2(29,:);
l_DE = in2(24,:);
l_IG = in2(25,:);
l_OA = in2(21,:);
l_OB = in2(22,:);
l_O_m1 = in2(16,:);
l_heela = in2(27,:);
m1 = in2(2,:);
m2 = in2(3,:);
m3 = in2(4,:);
m4 = in2(5,:);
m5 = in2(6,:);
ms = in2(7,:);
th1 = in1(3,:);
th2 = in1(4,:);
th3 = in1(5,:);
ths = in1(6,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = sin(th2);
t5 = th1+th2;
t6 = th2+th3;
t7 = sin(t5);
t8 = sin(t6);
t9 = t5+th3;
t10 = cos(t9);
t11 = sin(t9);
t12 = g.*l_AC.*m4.*t7;
t13 = g.*l_AC.*m5.*t7;
t14 = g.*l_A_m3.*m3.*t7;
t15 = g.*l_B_m2.*m2.*t7;
t16 = k.*l_DE.*l_IG.*t8;
t17 = k.*l_IG.*l_OB.*t8;
t18 = c5.*g.*m5.*t11;
t19 = k.*l_IG.*t10.*x;
t20 = k.*l_IG.*t11.*y;
t21 = -t19;
t22 = -t20;
Grav_Joint_Sp = [-k.*(-l_DE.*t3+l_IG.*t11+l_OA.*t3-l_OB.*t3+l_heela.*t3);g.*m1+g.*m2+g.*m3+g.*m4+g.*m5+g.*ms-k.*l_DE.*t2+k.*l_IG.*t10+k.*l_OA.*t2-k.*l_OB.*t2+k.*l_heela.*t2;t12+t13+t14+t15+t18+t21+t22+g.*l_C_m4.*m4.*t3+g.*l_DE.*m5.*t3+g.*l_OA.*m3.*t3+g.*l_OB.*m2.*t3+g.*l_OA.*m4.*t3+g.*l_OB.*m5.*t3+g.*l_O_m1.*m1.*t3+k.*l_DE.*t2.*x-k.*l_OA.*t2.*x+k.*l_OB.*t2.*x-k.*l_heela.*t2.*x+k.*l_DE.*t3.*y-k.*l_OA.*t3.*y+k.*l_OB.*t3.*y-k.*l_heela.*t3.*y;t12+t13+t14+t15+t16+t17+t18+t21+t22-k.*l_AC.*l_DE.*t4+k.*l_AC.*l_OA.*t4-k.*l_AC.*l_OB.*t4+k.*l_AC.*l_heela.*t4;t16+t17+t18+t21+t22+k.*l_AC.*l_IG.*sin(th3);g.*l_C_s.*ms.*sin(ths)];
