function Grav_Joint_Sp = Grav_leg(in1,in2)
%GRAV_LEG
%    GRAV_JOINT_SP = GRAV_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 10:40:24

c5 = in2(20,:);
g = in2(30,:);
k = in2(31,:);
l_AC = in2(23,:);
l_A_m3 = in2(18,:);
l_B_m2 = in2(17,:);
l_C_m4 = in2(19,:);
l_DE = in2(24,:);
l_IG = in2(25,:);
l_OA = in2(21,:);
l_OB = in2(22,:);
l_O_m1 = in2(16,:);
l_anklerest = in2(32,:);
l_heela = in2(27,:);
m1 = in2(2,:);
m2 = in2(3,:);
m3 = in2(4,:);
m4 = in2(5,:);
m5 = in2(6,:);
th1 = in1(3,:);
th2 = in1(4,:);
th3 = in1(5,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = sin(th3);
t5 = th1+th2;
t6 = th1+th3;
t7 = cos(t6);
t8 = sin(t5);
t9 = sin(t6);
t10 = k.*l_IG.*l_anklerest.*t7.*2.0;
t11 = c5.*g.*m5.*t9.*2.0;
t12 = k.*l_IG.*l_anklerest.*t9.*2.0;
t13 = -t10;
t14 = -t12;
Grav_Joint_Sp = [0.0;g.*(m1+m2+m3+m4+m5).*2.0;t11+t13+t14+g.*l_AC.*m4.*t8.*2.0+g.*l_AC.*m5.*t8.*2.0+g.*l_A_m3.*m3.*t8.*2.0+g.*l_B_m2.*m2.*t8.*2.0+g.*l_C_m4.*m4.*t3.*2.0+g.*l_DE.*m5.*t3.*2.0+g.*l_OA.*m3.*t3.*2.0+g.*l_OB.*m2.*t3.*2.0+g.*l_OA.*m4.*t3.*2.0+g.*l_OB.*m5.*t3.*2.0+g.*l_O_m1.*m1.*t3.*2.0+k.*l_DE.*l_anklerest.*t2.*2.0+k.*l_DE.*l_anklerest.*t3.*2.0-k.*l_OA.*l_anklerest.*t2.*2.0-k.*l_OA.*l_anklerest.*t3.*2.0+k.*l_OB.*l_anklerest.*t2.*2.0+k.*l_OB.*l_anklerest.*t3.*2.0-k.*l_anklerest.*l_heela.*t2.*2.0-k.*l_anklerest.*l_heela.*t3.*2.0;g.*t8.*(l_AC.*m4+l_AC.*m5+l_A_m3.*m3+l_B_m2.*m2).*2.0;t11+t13+t14+k.*l_DE.*l_IG.*t4.*2.0-k.*l_IG.*l_OA.*t4.*2.0+k.*l_IG.*l_OB.*t4.*2.0-k.*l_IG.*l_heela.*t4.*2.0;0.0;0.0;0.0];
