function Grav_Joint_Sp = Grav_leg(in1,in2)
%GRAV_LEG
%    GRAV_JOINT_SP = GRAV_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Nov-2021 15:42:49

g = in2(16,:);
l_AC = in2(26,:);
l_CE = in2(28,:);
l_DE = in2(27,:);
l_OB = in2(25,:);
l_m1 = in2(18,:);
l_m2 = in2(19,:);
l_m3 = in2(20,:);
l_m4 = in2(21,:);
l_ms = in2(22,:);
m1 = in2(2,:);
m2 = in2(3,:);
m3 = in2(4,:);
m4 = in2(5,:);
ms = in2(7,:);
th1 = in1(1,:);
th2 = in1(2,:);
ths = in1(3,:);
t2 = cos(th1);
t3 = th1+th2;
t4 = l_DE.*t2;
t5 = cos(t3);
t6 = l_AC.*t5;
t7 = -t6;
Grav_Joint_Sp = [g.*m2.*(l_CE.*t2-l_m2.*t5)+g.*m3.*(t4-l_m3.*t5)+g.*m4.*(t4+t7+l_m4.*t2)+g.*ms.*(t4+t7+l_OB.*t2)+g.*l_m1.*m1.*t2;-g.*t5.*(l_AC.*m4+l_m2.*m2+l_m3.*m3+l_AC.*ms);g.*l_ms.*ms.*cos(ths)];
