function Jleg = jacobian_foot(in1,in2)
%JACOBIAN_FOOT
%    JLEG = JACOBIAN_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Nov-2021 15:20:00

l_0A = in2(24,:);
l_AB = in2(25,:);
l_BC = in2(26,:);
l_CE = in2(28,:);
l_EG = in2(31,:);
th0 = in1(2,:);
th1 = in1(4,:);
th2 = in1(5,:);
ths = in1(3,:);
t2 = cos(th0);
t3 = sin(th0);
t4 = th1+ths;
t5 = cos(t4);
t6 = sin(t4);
t7 = t4+th2;
t8 = cos(t7);
t9 = sin(t7);
t10 = l_BC.*t5;
t11 = l_EG.*t5;
t12 = l_BC.*t6;
t13 = l_EG.*t6;
t14 = l_CE.*t8;
t15 = l_CE.*t9;
t16 = -t12;
t17 = -t13;
t18 = -t15;
Jleg = reshape([0.0,0.0,0.0,l_0A.*t3+l_AB.*t3+l_BC.*t3+l_CE.*t3+l_EG.*t3,-l_0A.*t2-l_AB.*t2-l_BC.*t2-l_CE.*t2-l_EG.*t2,0.0,t10+t11+t14+l_AB.*cos(ths),t16+t17+t18-l_AB.*sin(ths),0.0,t10+t11+t14,t16+t17+t18,0.0,t14,t18,0.0,0.0,0.0,0.0],[3,6]);
