function dJswing = jacobian_dot_swing(in1,in2)
%JACOBIAN_DOT_SWING
%    DJSWING = JACOBIAN_DOT_SWING(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Nov-2021 14:34:52

dth1 = in1(9,:);
dth2 = in1(10,:);
dth3 = in1(11,:);
l_AC = in2(23,:);
l_DE = in2(24,:);
l_GH = in2(26,:);
l_OB = in2(22,:);
th1 = in1(3,:);
th2 = in1(4,:);
th3 = in1(5,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = cos(t4);
t6 = sin(t4);
t7 = t4+th3;
t8 = cos(t7);
t9 = sin(t7);
t10 = l_AC.*t5;
t11 = l_AC.*t6;
t12 = l_GH.*t8;
t13 = l_GH.*t9;
t14 = dth3.*t12;
t15 = dth3.*t13;
t17 = t10+t12;
t18 = t11+t13;
t16 = -t15;
t19 = dth2.*t17;
t20 = dth2.*t18;
t21 = -t20;
dJswing = reshape([0.0,0.0,0.0,0.0,t16+t21-dth1.*(t18+l_DE.*t3+l_OB.*t3),t14+t19+dth1.*(t17+l_DE.*t2+l_OB.*t2),t16+t21-dth1.*t18,t14+t19+dth1.*t17,t16-dth1.*t13-dth2.*t13,t14+dth1.*t12+dth2.*t12,0.0,0.0],[2,6]);
