function Jtoe = jacobian_toe(in1,in2)
%JACOBIAN_TOE
%    JTOE = JACOBIAN_TOE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 15:44:46

l_AC = in2(23,:);
l_DE = in2(24,:);
l_GH = in2(26,:);
l_OB = in2(22,:);
th1 = in1(3,:);
th2 = in1(4,:);
th3 = in1(5,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = cos(t4);
t6 = sin(t4);
t7 = t4+th3;
t8 = cos(t7);
t9 = sin(t7);
t10 = l_AC.*t5;
t11 = l_AC.*t6;
t12 = l_GH.*t8;
t13 = l_GH.*t9;
Jtoe = reshape([1.0,0.0,0.0,1.0,t10+t12+l_DE.*t2+l_OB.*t2,t11+t13+l_DE.*t3+l_OB.*t3,t10+t12,t11+t13,t12,t13,0.0,0.0,0.0,0.0,0.0,0.0],[2,8]);
