function Jtoe2 = jacobian_toe2(in1,in2)
%JACOBIAN_TOE2
%    JTOE2 = JACOBIAN_TOE2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 10:40:30

l_AC = in2(23,:);
l_DE = in2(24,:);
l_GH = in2(26,:);
l_OB = in2(22,:);
th1 = in1(3,:);
th2 = in1(4,:);
th3 = in1(5,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = th1+th3;
t6 = cos(t4);
t7 = cos(t5);
t8 = sin(t4);
t9 = sin(t5);
t10 = l_AC.*t6;
t11 = l_GH.*t7;
t12 = l_AC.*t8;
t13 = l_GH.*t9;
Jtoe2 = reshape([1.0,0.0,0.0,1.0,t10+t11+l_DE.*t2+l_OB.*t2,t12+t13+l_DE.*t3+l_OB.*t3,t10,t12,t11,t13,0.0,0.0,0.0,0.0,0.0,0.0],[2,8]);
