function dJswing = jacobian_dot_swing(in1,in2)
%JACOBIAN_DOT_SWING
%    DJSWING = JACOBIAN_DOT_SWING(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    07-Dec-2021 19:52:09

dth1 = in1(4,:);
dth2 = in1(5,:);
dths = in1(6,:);
l_AC = in2(26,:);
l_DE = in2(27,:);
l_OB = in2(25,:);
ls = in2(23,:);
th1 = in1(1,:);
th2 = in1(2,:);
ths = in1(3,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = cos(t4);
t6 = sin(t4);
t7 = dth2.*l_AC.*t5;
t8 = dth2.*l_AC.*t6;
t9 = -t8;
dJswing = reshape([t7-dth1.*(-l_AC.*t5+l_DE.*t2+l_OB.*t2),t9+dth1.*(-l_AC.*t6+l_DE.*t3+l_OB.*t3),0.0,t7+dth1.*l_AC.*t5,t9-dth1.*l_AC.*t6,0.0,-dths.*ls.*cos(ths),dths.*ls.*sin(ths),0.0],[3,3]);
