function dJheel2 = jacobian_dot_heel2(in1,in2)
%JACOBIAN_DOT_HEEL2
%    DJHEEL2 = JACOBIAN_DOT_HEEL2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 15:44:52

dth21 = in1(14,:);
dth22 = in1(15,:);
dth23 = in1(16,:);
l_AC = in2(23,:);
l_DE = in2(24,:);
l_IG = in2(25,:);
l_OB = in2(22,:);
th21 = in1(6,:);
th22 = in1(7,:);
th23 = in1(8,:);
t2 = cos(th21);
t3 = sin(th21);
t4 = th21+th22;
t5 = cos(t4);
t6 = sin(t4);
t7 = t4+th23;
t8 = cos(t7);
t9 = sin(t7);
t10 = l_AC.*t5;
t11 = l_AC.*t6;
t12 = l_IG.*t8;
t13 = l_IG.*t9;
t14 = dth23.*t12;
t15 = dth23.*t13;
t16 = -t12;
t17 = -t13;
t18 = -t14;
t19 = t10+t16;
t20 = t11+t17;
t21 = dth22.*t19;
t22 = dth22.*t20;
t23 = -t22;
dJheel2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t15+t23-dth21.*(t20+l_DE.*t3+l_OB.*t3),t18+t21+dth21.*(t19+l_DE.*t2+l_OB.*t2),t15+t23-dth21.*t20,t18+t21+dth21.*t19,t15+dth21.*t13+dth22.*t13,t18+dth21.*t16+dth22.*t16],[2,8]);
