function dJtoe2 = jacobian_dot_toe2(in1,in2)
%JACOBIAN_DOT_TOE2
%    DJTOE2 = JACOBIAN_DOT_TOE2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 15:44:51

dth21 = in1(14,:);
dth22 = in1(15,:);
dth23 = in1(16,:);
l_AC = in2(23,:);
l_DE = in2(24,:);
l_GH = in2(26,:);
l_OB = in2(22,:);
th21 = in1(6,:);
th22 = in1(7,:);
th23 = in1(8,:);
t2 = cos(th21);
t3 = sin(th21);
t4 = th21+th22;
t5 = cos(t4);
t6 = sin(t4);
t7 = t4+th23;
t8 = cos(t7);
t9 = sin(t7);
t10 = l_AC.*t5;
t11 = l_AC.*t6;
t12 = l_GH.*t8;
t13 = l_GH.*t9;
t14 = dth23.*t12;
t15 = dth23.*t13;
t17 = t10+t12;
t18 = t11+t13;
t16 = -t15;
t19 = dth22.*t17;
t20 = dth22.*t18;
t21 = -t20;
dJtoe2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t16+t21-dth21.*(t18+l_DE.*t3+l_OB.*t3),t14+t19+dth21.*(t17+l_DE.*t2+l_OB.*t2),t16+t21-dth21.*t18,t14+t19+dth21.*t17,t16-dth21.*t13-dth22.*t13,t14+dth21.*t12+dth22.*t12],[2,8]);
