function dJswing = jacobian_dot_swing(in1,in2)
%JACOBIAN_DOT_SWING
%    DJSWING = JACOBIAN_DOT_SWING(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 09:39:16

dths = in1(12,:);
ls = in2(28,:);
ths = in1(6,:);
dJswing = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dths.*ls.*sin(ths),-dths.*ls.*cos(ths)],[2,6]);
