function Jswing = jacobian_toe_swing(in1,in2)
%JACOBIAN_TOE_SWING
%    JSWING = JACOBIAN_TOE_SWING(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 09:39:15

ls = in2(28,:);
ths = in1(6,:);
Jswing = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,ls.*cos(ths),-ls.*sin(ths)],[2,6]);
