function dJtoe2 = jacobian_dot_toe2(in1,in2)
%JACOBIAN_DOT_TOE2
%    DJTOE2 = JACOBIAN_DOT_TOE2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 10:40:30

dth1 = in1(11,:);
dth2 = in1(12,:);
dth3 = in1(13,:);
l_AC = in2(23,:);
l_DE = in2(24,:);
l_GH = in2(26,:);
l_OB = in2(22,:);
th1 = in1(3,:);
th2 = in1(4,:);
th3 = in1(5,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = th1+th3;
t6 = cos(t4);
t7 = cos(t5);
t8 = sin(t4);
t9 = sin(t5);
t10 = dth2.*l_AC.*t6;
t11 = dth3.*l_GH.*t7;
t12 = dth2.*l_AC.*t8;
t13 = dth3.*l_GH.*t9;
t14 = -t12;
t15 = -t13;
dJtoe2 = reshape([0.0,0.0,0.0,0.0,t14+t15-dth1.*(l_AC.*t8+l_DE.*t3+l_GH.*t9+l_OB.*t3),t10+t11+dth1.*(l_AC.*t6+l_DE.*t2+l_GH.*t7+l_OB.*t2),t14-dth1.*l_AC.*t8,t10+dth1.*l_AC.*t6,t15-dth1.*l_GH.*t9,t11+dth1.*l_GH.*t7,0.0,0.0,0.0,0.0,0.0,0.0],[2,8]);
