function dJankle2 = jacobian_dot_ankle2f(in1,in2)
%JACOBIAN_DOT_ANKLE2F
%    DJANKLE2 = JACOBIAN_DOT_ANKLE2F(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 10:40:33

dth1 = in1(11,:);
dth2 = in1(12,:);
l_AC = in2(23,:);
l_DE = in2(24,:);
l_OB = in2(22,:);
th1 = in1(3,:);
th2 = in1(4,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = cos(t4);
t6 = sin(t4);
t7 = dth2.*l_AC.*t5;
t8 = dth2.*l_AC.*t6;
t9 = -t8;
dJankle2 = reshape([0.0,0.0,0.0,0.0,t9-dth1.*(l_AC.*t6+l_DE.*t3+l_OB.*t3),t7+dth1.*(l_AC.*t5+l_DE.*t2+l_OB.*t2),t9-dth1.*l_AC.*t6,t7+dth1.*l_AC.*t5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,8]);
