function dJankle2 = jacobian_dot_ankle2f(in1,in2)
%JACOBIAN_DOT_ANKLE2F
%    DJANKLE2 = JACOBIAN_DOT_ANKLE2F(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 15:44:53

dth21 = in1(14,:);
dth22 = in1(15,:);
l_AC = in2(23,:);
l_DE = in2(24,:);
l_OB = in2(22,:);
th21 = in1(6,:);
th22 = in1(7,:);
t2 = cos(th21);
t3 = sin(th21);
t4 = th21+th22;
t5 = cos(t4);
t6 = sin(t4);
t7 = dth22.*l_AC.*t5;
t8 = dth22.*l_AC.*t6;
t9 = -t8;
dJankle2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t9-dth21.*(l_AC.*t6+l_DE.*t3+l_OB.*t3),t7+dth21.*(l_AC.*t5+l_DE.*t2+l_OB.*t2),t9-dth21.*l_AC.*t6,t7+dth21.*l_AC.*t5,0.0,0.0],[2,8]);
