function Jtoes = jacobian_toe_swing(in1,in2)
%JACOBIAN_TOE_SWING
%    JTOES = JACOBIAN_TOE_SWING(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Nov-2021 15:49:05

ls = in2(28,:);
ths = in1(6,:);
Jtoes = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ls.*cos(ths),ls.*sin(ths),0.0],[3,6]);
