function keypoints = keypoints_leg(in1,in2)
%KEYPOINTS_LEG
%    KEYPOINTS = KEYPOINTS_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Nov-2021 15:20:01

l_0A = in2(24,:);
l_AB = in2(25,:);
l_BC = in2(26,:);
l_BD = in2(27,:);
l_CE = in2(28,:);
l_DF = in2(29,:);
l_EG = in2(31,:);
th0 = in1(2,:);
th1 = in1(4,:);
th2 = in1(5,:);
ths = in1(3,:);
x = in1(1,:);
t2 = cos(th0);
t3 = cos(ths);
t4 = sin(th0);
t5 = sin(ths);
t6 = th1+ths;
t7 = l_0A.*t2;
t8 = cos(t6);
t9 = l_0A.*t4;
t10 = sin(t6);
t11 = t6+th2;
t14 = -t2;
t15 = -t4;
t16 = -t5;
t12 = cos(t11);
t13 = sin(t11);
t17 = -t7;
t18 = -t9;
t19 = t2+t16;
t20 = t3+t15;
t23 = t8+t15;
t24 = t10+t14;
t27 = -l_BC.*(t4-t8);
t28 = -l_BC.*(t2-t10);
t29 = -l_BD.*(t4-t8);
t30 = -l_BD.*(t2-t10);
t21 = l_AB.*t19;
t22 = l_AB.*t20;
t25 = t12+t15;
t26 = t13+t14;
t32 = -l_CE.*(t4-t12);
t33 = -l_CE.*(t2-t13);
t31 = -t21;
keypoints = reshape([x,0.0,t17,t18,t17+t31,t18+t22,t17+t28+t31,t18+t22+t27,t17+t30+t31,t18+t22+t29,t17+t28+t31+t33,t18+t22+t27+t32,t17+t30+t31-l_DF.*(t2-t13),t18+t22+t29-l_DF.*(t4-t12),t17+t28+t31+t33-l_EG.*(t2-t10),t18+t22+t27+t32-l_EG.*(t4-t8)],[2,8]);
