function keypoints = keypoints_leg(in1,in2)
%KEYPOINTS_LEG
%    KEYPOINTS = KEYPOINTS_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    16-Nov-2021 13:35:27

l_AC = in2(21,:);
l_DE = in2(22,:);
l_GH = in2(24,:);
l_IG = in2(23,:);
l_OA = in2(19,:);
l_OB = in2(20,:);
l_heela = in2(25,:);
th1 = in1(3,:);
th2 = in1(4,:);
th3 = in1(5,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l_DE.*t2;
t6 = l_OA.*t2;
t7 = l_OB.*t2;
t8 = cos(t4);
t9 = l_DE.*t3;
t10 = l_OA.*t3;
t11 = l_OB.*t3;
t12 = sin(t4);
t13 = t4+th3;
t14 = cos(t13);
t15 = sin(t13);
t16 = l_AC.*t8;
t17 = l_AC.*t12;
t18 = -t5;
t19 = -t6;
t20 = -t7;
t21 = -t16;
keypoints = reshape([x,y,t10+x,t19+y,t11+x,t20+y,t10+t17+x,t19+t21+y,t11+t17+x,t20+t21+y,t9+t11+t17+x,t18+t20+t21+y,t9+t11+t17+x-l_IG.*t15,t18+t20+t21+y+l_IG.*t14,t9+t11+t17+x+l_GH.*t15,t18+t20+t21+y-l_GH.*t14,t10+t17+x+l_heela.*t3,t19+t21+y-l_heela.*t2],[2,9]);
