function keypoints = keypoints_leg(in1,in2)
%KEYPOINTS_LEG
%    KEYPOINTS = KEYPOINTS_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Nov-2021 15:42:52

l_AC = in2(26,:);
l_CE = in2(28,:);
l_DE = in2(27,:);
l_IG = in2(29,:);
l_OB = in2(25,:);
l_heela = in2(31,:);
ls = in2(23,:);
th1 = in1(1,:);
th2 = in1(2,:);
ths = in1(3,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l_CE.*t2;
t6 = l_DE.*t2;
t7 = l_OB.*t2;
t8 = cos(t4);
t9 = l_CE.*t3;
t10 = l_DE.*t3;
t11 = l_OB.*t3;
t12 = sin(t4);
t13 = l_AC.*t8;
t14 = l_AC.*t12;
t15 = -t9;
t16 = -t10;
t17 = -t11;
t18 = -t13;
keypoints = reshape([t6+t7+t18,t14+t16+t17,t5+t18,t14+t15,t6+t18,t14+t16,t5,t15,t6,t16,-l_IG,0.0,l_heela.*t2,-l_heela.*t3,t6+t7+t18+ls.*cos(ths),t14+t16+t17-ls.*sin(ths)],[2,8]);
