function rHs = position_toe_swing(in1,in2)
%POSITION_TOE_SWING
%    RHS = POSITION_TOE_SWING(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    30-Nov-2021 15:22:40

l_AC = in2(26,:);
l_DE = in2(27,:);
l_OB = in2(25,:);
ls = in2(23,:);
th1 = in1(1,:);
th2 = in1(2,:);
ths = in1(3,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
rHs = [l_DE.*t2+l_OB.*t2-l_AC.*cos(t4)+ls.*cos(ths);-l_DE.*t3-l_OB.*t3+l_AC.*sin(t4)-ls.*sin(ths);0.0];
