function rHs = position_toe_swing(in1,in2)
%POSITION_TOE_SWING
%    RHS = POSITION_TOE_SWING(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Nov-2021 14:34:51

ls = in2(28,:);
ths = in1(6,:);
x = in1(1,:);
y = in1(2,:);
rHs = [x+ls.*sin(ths);y-ls.*cos(ths);0.0];
