function r2I = position_heel2(in1,in2)
%POSITION_HEEL2
%    R2I = POSITION_HEEL2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 15:44:51

l_AC = in2(23,:);
l_DE = in2(24,:);
l_IG = in2(25,:);
l_OB = in2(22,:);
th21 = in1(6,:);
th22 = in1(7,:);
th23 = in1(8,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th21);
t3 = sin(th21);
t4 = th21+th22;
t5 = t4+th23;
r2I = [x+l_DE.*t3+l_OB.*t3+l_AC.*sin(t4)-l_IG.*sin(t5);y-l_DE.*t2-l_OB.*t2-l_AC.*cos(t4)+l_IG.*cos(t5);0.0];
