function r_heela = position_ankle(in1,in2)
%POSITION_ANKLE
%    R_HEELA = POSITION_ANKLE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    07-Dec-2021 16:33:55

l_heela = in2(31,:);
th1 = in1(1,:);
r_heela = [l_heela.*cos(th1);-l_heela.*sin(th1);0.0];
