function r_EG = position_foot(in1,in2)
%POSITION_FOOT
%    R_EG = POSITION_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Nov-2021 15:20:00

l_0A = in2(24,:);
l_AB = in2(25,:);
l_BC = in2(26,:);
l_CE = in2(28,:);
l_EG = in2(31,:);
th0 = in1(2,:);
th1 = in1(4,:);
th2 = in1(5,:);
ths = in1(3,:);
t2 = cos(th0);
t3 = sin(th0);
t4 = th1+ths;
t5 = cos(t4);
t6 = sin(t4);
t7 = t4+th2;
t8 = -t2;
t9 = -t3;
t10 = t5+t9;
t11 = t6+t8;
r_EG = [l_0A.*t8-l_BC.*(t2-t6)-l_EG.*(t2-t6)-l_CE.*(t2-sin(t7))-l_AB.*(t2-sin(ths));l_0A.*t9-l_BC.*(t3-t5)-l_EG.*(t3-t5)-l_CE.*(t3-cos(t7))-l_AB.*(t3-cos(ths));0.0];
