function dr2H = velocity_toe2(in1,in2)
%VELOCITY_TOE2
%    DR2H = VELOCITY_TOE2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 15:44:50

dth21 = in1(14,:);
dth22 = in1(15,:);
dth23 = in1(16,:);
dx = in1(9,:);
dy = in1(10,:);
l_AC = in2(23,:);
l_DE = in2(24,:);
l_GH = in2(26,:);
l_OB = in2(22,:);
th21 = in1(6,:);
th22 = in1(7,:);
th23 = in1(8,:);
t2 = cos(th21);
t3 = sin(th21);
t4 = th21+th22;
t5 = cos(t4);
t6 = sin(t4);
t7 = t4+th23;
t8 = cos(t7);
t9 = sin(t7);
t10 = l_AC.*t5;
t11 = l_AC.*t6;
t12 = l_GH.*t8;
t13 = l_GH.*t9;
dr2H = [dx+dth22.*(t10+t12)+dth23.*t12+dth21.*(t10+t12+l_DE.*t2+l_OB.*t2);dy+dth22.*(t11+t13)+dth23.*t13+dth21.*(t11+t13+l_DE.*t3+l_OB.*t3);0.0];
