function dr_EG = velocity_foot(in1,in2)
%VELOCITY_FOOT
%    DR_EG = VELOCITY_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Nov-2021 15:20:00

dth0 = in1(8,:);
dth1 = in1(10,:);
dth2 = in1(11,:);
dths = in1(9,:);
l_0A = in2(24,:);
l_AB = in2(25,:);
l_BC = in2(26,:);
l_CE = in2(28,:);
l_EG = in2(31,:);
th0 = in1(2,:);
th1 = in1(4,:);
th2 = in1(5,:);
ths = in1(3,:);
t2 = cos(th0);
t3 = sin(th0);
t4 = th1+ths;
t5 = cos(t4);
t6 = sin(t4);
t7 = t4+th2;
t8 = cos(t7);
t9 = sin(t7);
t10 = l_BC.*t5;
t11 = l_EG.*t5;
t12 = l_BC.*t6;
t13 = l_EG.*t6;
t14 = l_CE.*t8;
t15 = l_CE.*t9;
dr_EG = [dths.*(t10+t11+t14+l_AB.*cos(ths))+dth2.*t14+dth0.*(l_0A.*t3+l_AB.*t3+l_BC.*t3+l_CE.*t3+l_EG.*t3)+dth1.*(t10+t11+t14);-dths.*(t12+t13+t15+l_AB.*sin(ths))-dth2.*t15-dth0.*(l_0A.*t2+l_AB.*t2+l_BC.*t2+l_CE.*t2+l_EG.*t2)-dth1.*(t12+t13+t15);0.0];
