function dr2E = velocity_ankle2(in1,in2)
%VELOCITY_ANKLE2
%    DR2E = VELOCITY_ANKLE2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 15:44:53

dth21 = in1(14,:);
dth22 = in1(15,:);
dx = in1(9,:);
dy = in1(10,:);
l_AC = in2(23,:);
l_DE = in2(24,:);
l_OB = in2(22,:);
th21 = in1(6,:);
th22 = in1(7,:);
t2 = cos(th21);
t3 = sin(th21);
t4 = th21+th22;
t5 = cos(t4);
t6 = sin(t4);
dr2E = [dx+dth21.*(l_AC.*t5+l_DE.*t2+l_OB.*t2)+dth22.*l_AC.*t5;dy+dth21.*(l_AC.*t6+l_DE.*t3+l_OB.*t3)+dth22.*l_AC.*t6;0.0];
