function drH = velocity_toe(in1,in2)
%VELOCITY_TOE
%    DRH = VELOCITY_TOE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2021 10:40:26

dth1 = in1(11,:);
dth2 = in1(12,:);
dth3 = in1(13,:);
dx = in1(9,:);
dy = in1(10,:);
l_AC = in2(23,:);
l_DE = in2(24,:);
l_GH = in2(26,:);
l_OB = in2(22,:);
th1 = in1(3,:);
th2 = in1(4,:);
th3 = in1(5,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = th1+th3;
t6 = cos(t4);
t7 = cos(t5);
t8 = sin(t4);
t9 = sin(t5);
drH = [dx+dth1.*(l_AC.*t6+l_DE.*t2+l_GH.*t7+l_OB.*t2)+dth2.*l_AC.*t6+dth3.*l_GH.*t7;dy+dth1.*(l_AC.*t8+l_DE.*t3+l_GH.*t9+l_OB.*t3)+dth2.*l_AC.*t8+dth3.*l_GH.*t9;0.0];
